services:
  hdd:
    build:
      context: .
      dockerfile: hdd/Dockerfile
    image: hdd:babah
    container_name: hdd-monitor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/Data/Backup:/mnt/Data/Backup
      - /mnt/Data/Syslog:/mnt/Data/Syslog
    environment:
      BACKUP_DIR: "/mnt/Data/Backup"
    ports:
      - "5000:5000"
    networks:
      rtsp-syslog-network:
        ipv4_address: 172.16.31.2

  logrotate:
    build:
      context: .
      dockerfile: syslog/Dockerfile
    image: logrotate:babah
    container_name: logrotate
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/Data/Syslog/default/logrotate:/mnt/Data/Syslog/default/logrotate
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    depends_on:
      - syslog-ng
    restart: "no"
    networks:
      rtsp-syslog-network:
        ipv4_address: 172.16.31.3

  syslog-ng:
    build:
      context: .
      dockerfile: syslog/Dockerfile
    image: syslog-ng:babah
    container_name: syslog-ng
    ports:
      - "1514:1514/tcp"
      - "1514:1514/udp"
    restart: always
    hostname: ${SYSLOG_HOSTNAME:-syslog-ng}
    user: root
    cap_add:
      - CAP_NET_BIND_SERVICE
    command: ["syslog-ng", "--foreground", "-f", "/app/syslog/config/syslog-ng.conf", "--persist-file=/mnt/Data/Syslog/var-run/syslog-ng.persist"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/Data/Syslog:/mnt/Data/Syslog
      - /mnt/Data/Syslog/var-run:/mnt/Data/Syslog/var-run
      - /home/abdullah/config:/app/syslog/config
    networks:
      rtsp-syslog-network:
        ipv4_address: 172.16.31.4

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-socket-proxy
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      LOGS: 1
    networks:
      rtsp-syslog-network:
        ipv4_address: 172.16.31.5

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: api:babah
    container_name: api-monitor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/Data/Backup:/mnt/Data/Backup
      - /mnt/Data/Syslog:/mnt/Data/Syslog
      - ./api/data:/app/data
    environment:
      LOG_DIR: "/app/data"
    ports:
      - "5001:5001"
    networks:
      rtsp-syslog-network:
        ipv4_address: 172.16.31.6

networks:
  rtsp-syslog-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.31.0/28"
          gateway: "172.16.31.1"