services:
  hdd:
    build:
      context: .
      dockerfile: hdd/Dockerfile
    image: hdd-monitor
    container_name: hdd-monitor
    restart: always
    volumes:
      - syslog-data:/mnt/Data/Syslog
      - /mnt/Data/Backup:/mnt/Data/Backup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      BACKUP_DIR: "/mnt/Data/Backup"
    networks:
      - babah-network

  syslog:
    build:
      context: ./syslog
      dockerfile: Dockerfile
    image: syslog-ng
    container_name: syslog-ng
    restart: always
    hostname: ${SYSLOG_HOSTNAME:-syslog-ng}
    cap_add:
      - CAP_NET_BIND_SERVICE
    command: ["syslog-ng", "--foreground", "-f", "/app/syslog/config/syslog-ng.conf", "--persist-file=/app/syslog/var-run/syslog-ng.persist"]
    volumes:
      - syslog-data:/mnt/Data/Syslog
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/log_messages.json:/app/syslog/config/log_messages.json:ro
    networks:
      - babah-network

  logrotate:
    build:
      context: ./syslog
      dockerfile: Dockerfile
    image: logrotate
    container_name: logrotate
    depends_on:
      - syslog
    restart: on-failure
    volumes:
      - syslog-data:/mnt/Data/Syslog
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/log_messages.json:/app/syslog/config/log_messages.json:ro
    networks:
      - babah-network

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: api-monitor
    container_name: api-monitor
    restart: always
    volumes:
      - /mnt/Data/Backup:/mnt/Data/Backup
      - syslog-data:/mnt/Data/Syslog
      - ./api/data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      LOG_DIR: "/app/data"
    networks:
      - babah-network

  stream:
    build:
      context: ./
      dockerfile: streamserver/Dockerfile
    image: stream-server
    container_name: stream-server
    depends_on:
      - syslog
    # Jalankan sebagai root (jika masih butuh chown / chmod volume host)
    # user: "0:0" 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./streamserver/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/log_messages.json:/app/streamserver/config/log_messages.json:ro
      - ./config/credentials.sh:/app/streamserver/config/credentials.sh:ro
      # Named volume:
      - stream-temp-data:/app/streamserver/temp/stream
      # Jika masih mau simpan ke host, pakai ini:
      # - /mnt/Data/Syslog/stream:/app/streamserver/temp/stream
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - babah-network

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: babah-docker-socket-proxy
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      LOGS: 1
    networks:
      - babah-network

volumes:
  syslog-data:
    name: data-syslog
  stream-temp-data:
    name: stream-temp-data

networks:
  babah-network:
    name: babah-network
    driver: bridge
