services:
  hdd-monitor:
    build: ./hdd
    image: hdd-monitor:latest
    container_name: hdd-monitor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/log_messages.json:/app/config/log_messages.json:ro
      - /mnt/Data/Backup:/mnt/Data/Backup
      - /mnt/Data/Syslog:/mnt/Data/Syslog
    environment:
      BACKUP_DIR: "/mnt/Data/Backup"
    ports:
      - "5000:5000"

  logrotate-setup:
    image: alpine:latest
    container_name: logrotate-setup
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/generate_logrotate.sh:/app/generate_logrotate.sh
      - /mnt/Data/Syslog/default/logrotate:/mnt/Data/Syslog/default/logrotate
      - ./syslog/logrotate:/app/logrotate
      - ./config/log_messages.json:/app/config/log_messages.json:ro
    user: root
    depends_on:
      - syslog-ng
    restart: "no"
    networks:
      rtsp-syslog-network:
        ipv4_address: 172.16.31.2

  syslog-ng:
    build: ./syslog
    container_name: syslog-ng
    ports:
      - "1514:1514/tcp"
      - "1514:1514/udp"
    restart: always
    hostname: ${SYSLOG_HOSTNAME:-syslog-ng}
    cap_add:
      - CAP_SYS_ADMIN
      - CAP_NET_BIND_SERVICE
    command: ["syslog-ng", "--foreground", "-f", "/app/config/syslog-ng.conf", "--persist-file=/run/syslog-ng.persist"]
    volumes:
      - /mnt/Data/Syslog:/mnt/Data/Syslog
      - ./syslog/config/syslog-ng.conf:/app/config/syslog-ng.conf:ro
      - /mnt/Data/Syslog/var-run:/run
      - /mnt/Data/Syslog/default:/mnt/Data/Syslog/default
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/log_messages.json:/app/config/log_messages.json:ro
    env_file:
      - .env
    environment:
      SYSLOG_USER: ${SYSLOG_USER:-root}
      SYSLOG_PORT: ${SYSLOG_PORT:-1514}
    networks:
      rtsp-syslog-network:
        ipv4_address: 172.16.31.3

networks:
  rtsp-syslog-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.31.0/28"
          gateway: "172.16.31.1"