services:
  hdd:
    build:
      context: ./hdd
      dockerfile: Dockerfile
    image: hdd-monitor
    container_name: hdd-monitor
    restart: always
    volumes:
      - syslog-data:/mnt/Data/Syslog
      - /mnt/Data/Backup:/mnt/Data/Backup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      BACKUP_DIR: "/mnt/Data/Backup"
    networks:
      rtsp-syslog-network:

  syslog:
    build: 
      context: ./syslog
      dockerfile: Dockerfile
    image: syslog-ng
    container_name: syslog-ng
    restart: unless-stopped
    hostname: ${SYSLOG_HOSTNAME:-syslog-ng}
    cap_add:
      - CAP_NET_BIND_SERVICE
    command: ["syslog-ng", "--foreground", "-f", "/app/syslog/config/syslog-ng.conf", "--persist-file=/app/syslog/var-run/syslog-ng.persist"]
    environment:
      LOG_MESSAGES_FILE: "/app/config/log_messages.json"
    ports:
      - "1514:1514/tcp"
      - "1514:1514/udp"
    entrypoint: ["/app/syslog/entrypoint.sh"]
    volumes:
      - syslog-data:/app/Syslog
      - /mnt/Data/Syslog:/mnt/Data/Syslog
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/log_messages.json:/app/syslog/config/log_messages.json:ro
    networks:
      rtsp-syslog-network:
    healthcheck:
      test: ["CMD", "pgrep", "syslog-ng"]
      interval: 30s
      timeout: 10s
      retries: 3

  logrotate:
    build:
      context: ./syslog
      dockerfile: Dockerfile
    image: logrotate
    container_name: logrotate
    ports: []
    depends_on:
      - syslog
    restart: on-failure
    entrypoint: ["/app/syslog/entrypoint-logrotate.sh"]
    environment:
      LOG_MESSAGES_FILE: "/app/config/syslog/log_messages.json"
    volumes:
      - syslog-data:/app/Syslog:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/Data/Syslog:/mnt/Data/Syslog
      - ./config/log_messages.json:/app/syslog/config/log_messages.json:ro
    networks:
      rtsp-syslog-network:
    healthcheck:
      test: ["CMD", "pgrep", "syslog-ng"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api-monitor
    container_name: api-monitor
    restart: always
    volumes:
      - /mnt/Data/Backup:/mnt/Data/Backup
      - syslog-data:/mnt/Data/Syslog
      - ./api/data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      LOG_DIR: "/app/data"
    networks:
      rtsp-syslog-network:

  stream:
    build:
      context: .
      dockerfile: ./streamserver/Dockerfile
    image: stream-server
    container_name: stream-server

    volumes:
      # Folder scripts
      - ./scripts:/app/scripts:rw
      # File konfigurasi log messages
      - ./config/log_messages.json:/app/config/log_messages.json:ro
      # Folder konfigurasi Nginx
      - ./streamserver/config:/etc/nginx
      # Temp folder untuk HLS
      - ./temp/stream:/app/streamserver/temp/stream
      # Direktori log terpusat di TrueNAS
      - /mnt/Data/Syslog/rtsp/nginx:/var/log/nginx
      - /mnt/Data/Syslog/rtsp/stream:/var/log/stream
      # File kredensial
      - ./config/credentials.sh:/app/streamserver/config/credentials.sh:ro

      # Bind-mount Data Sistem
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/Data/Syslog:/mnt/Data/Syslog

    # Mode jaringan host
    network_mode: "host"

    # Healthcheck untuk memonitor layanan
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hls"]
      interval: 30s
      timeout: 10s
      retries: 3

    depends_on:
      - syslog

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: babah-docker-socket-proxy
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      LOGS: 1
    networks:
      rtsp-syslog-network:

networks:
  rtsp-syslog-network:
    name: babah-network
    driver: bridge

volumes:
  syslog-data:
    name: data-syslog
  stream-temp-data:
    name: stream-temp-data
