networks:
  rtsp-syslog-network:
    name: babah-network
    driver: bridge

volumes:
  syslog-data:
    driver: local
    name: data-syslog
  nginx-data:
    driver: local
    name: nginx-data
  scripts-data:
    driver: local
    name: scripts-data
  hls-data:
    driver: local
    name: hls-data

services:
  # =========================================================
  # HDD Monitor (misalnya memantau /mnt/Data/Backup dsb.)
  # =========================================================
  hdd:
    build:
      context: ./hdd
      dockerfile: Dockerfile
    image: hdd-monitor
    container_name: hdd-monitor
    restart: always
    volumes:
      - syslog-data:/mnt/Data/Syslog
      - /mnt/Data/Backup:/mnt/Data/Backup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      BACKUP_DIR: "/mnt/Data/Backup"
    networks:
      rtsp-syslog-network:

  # =========================================================
  # Syslog (syslog-ng)
  # =========================================================
  syslog:
    build: 
      context: ./syslog
      dockerfile: Dockerfile
    image: syslog-ng
    container_name: syslog-ng
    hostname: ${SYSLOG_HOSTNAME:-syslog-ng}
    restart: unless-stopped
    command: ["syslog-ng", "--foreground", "-f", "/app/syslog/config/syslog-ng.conf", "--persist-file=/app/syslog/var-run/syslog-ng.persist"]
    ports:
      - "1514:1514/tcp"
      - "1514:1514/udp"
    entrypoint: ["/app/syslog/entrypoint.sh"]
    volumes:
      - syslog-data:/app/Syslog
      - /mnt/Data/Syslog:/mnt/Data/Syslog
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/log_messages.json:/app/syslog/config/log_messages.json:ro
    environment:
      LOG_MESSAGES_FILE: "/app/config/log_messages.json"
    networks:
      rtsp-syslog-network:
    healthcheck:
      test: ["CMD", "pgrep", "syslog-ng"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =========================================================
  # Logrotate (opsional, memutar log syslog)
  # =========================================================
  logrotate:
    build:
      context: ./syslog
      dockerfile: Dockerfile
    image: logrotate
    container_name: logrotate
    depends_on:
      - syslog
    restart: on-failure
    entrypoint: ["/app/syslog/entrypoint-logrotate.sh"]
    environment:
      LOG_MESSAGES_FILE: "/app/config/syslog/log_messages.json"
    volumes:
      - syslog-data:/app/Syslog:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/Data/Syslog:/mnt/Data/Syslog
      - ./config/log_messages.json:/app/syslog/config/log_messages.json:ro
    networks:
      rtsp-syslog-network:
    healthcheck:
      test: ["CMD", "pgrep", "syslog-ng"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =========================================================
  # API Monitor (contoh)
  # =========================================================
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api-monitor
    container_name: api-monitor
    restart: always
    volumes:
      - /mnt/Data/Backup:/mnt/Data/Backup
      #- syslog-data:/mnt/Data/Syslog
      - ./api/data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      LOG_DIR: "/app/data"
    networks:
      rtsp-syslog-network:

  # =========================================================
  # Stream Server (Nginx-RTMP) 
  # =========================================================
  stream:
    build:
      context: .
      dockerfile: ./streamserver/Dockerfile
    image: stream-server
    container_name: stream-server
    network_mode: "host"

    volumes:
      # Folder scripts (Python, dsb.)
      - ./scripts:/app/scripts

      # File konfigurasi log messages
      - ./config:/app/config

      # File konfigurasi log messages
      #- ./streamserver:/app/streamserver

      # File konfigurasi log messages
      - hls-data:/app/hls

      # Volume
      - /mnt/Data/Syslog:/mnt/Data/Syslog

      # Bind-mount Data Sistem (opsional, jika perlu akses /mnt/Data/Syslog)
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    depends_on:
      - syslog
    env_file:
      - .env

    # Healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/hls/stream.m3u8"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =========================================================
  # Docker Socket Proxy (opsional)
  # =========================================================
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: babah-docker-socket-proxy
    privileged: true
    restart: unless-stopped
    networks:
      rtsp-syslog-network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      LOGS: 1