version: '3.9'
services:
  # =========================================================
  # Syslog (syslog-ng)
  # =========================================================
  syslog:
    build: 
      context: .
      dockerfile: ./syslog/Dockerfile
    image: syslog-ng
    container_name: syslog-ng
    hostname: ${SYSLOG_HOSTNAME:-syslog-ng}
    restart: unless-stopped
    command: ["syslog-ng", "--foreground", "-f", "/app/syslog/config/syslog-ng.conf", "--persist-file=/app/syslog/var-run/syslog-ng.persist"]
    ports:
      - "1514:1514/tcp"
      - "1514:1514/udp"
    entrypoint: ["/app/syslog/entrypoint.sh"]
    volumes:
      - syslog-data:/mnt/Data/Syslog
      - logrotate-data:/app/syslog/logrotate
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      LOG_MESSAGES_FILE: "/app/config/log_messages.json"
    networks:
      babahdigital:
    healthcheck:
      test: ["CMD", "pgrep", "syslog-ng"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =========================================================
  # Logrotate
  # =========================================================
  logrotate:
    build:
      context: .
      dockerfile: ./syslog/Dockerfile
    image: logrotate
    container_name: logrotate
    depends_on:
      - syslog
    restart: on-failure
    entrypoint: ["/app/syslog/entrypoint-logrotate.sh"]
    environment:
      LOG_MESSAGES_FILE: "/app/config/log_messages.json"
    volumes:
      - syslog-data:/mnt/Data/Syslog
      - logrotate-data:/app/syslog/logrotate
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      babahdigital:
    healthcheck:
      test: ["CMD", "pgrep", "syslog-ng"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =========================================================
  # Stream Server (Nginx-RTMP) 
  # =========================================================
  stream:
    build:
      context: .
      dockerfile: ./streamserver/Dockerfile
    image: stream-server
    container_name: stream-server
    networks:
      babahdigital:
    #network_mode: "host"
    ports:
      # HLS Services
      - "80:8080"
    volumes:
      # Folder scripts (Python, dsb.)
      - ./scripts:/app/scripts
      # File konfigurasi log messages
      - ./config:/app/config
      # File hls
      - hls-data:/app/hls
      # Bind Syslog Truenas
      - syslog-data:/mnt/Data/Syslog
      # Bind-mount Data Sistem
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Credentials RTSP
      - secret-rtsp:/app/config/credentials.sh:ro
    depends_on:
      - syslog
    env_file:
      - .env
    secrets:
      - rtsp_user
      - rtsp_password

networks:
  babahdigital:
    name: babah-network
    driver: overlay

volumes:
  syslog-data:
    driver: local
    name: syslog-data
    driver_opts:
      type: nfs
      o: addr=172.16.30.2,nolock
      device: /mnt/Data/Syslog
  backup-data:
    driver: local
    name: backup-data
    driver_opts:
      type: none
      o: bind
      device: /mnt/Data/Backup
  logrotate-data:
    driver: local
    name: logrotate-data
  hls-data:
    driver: local
    name: hls-data
  secret-rtsp:
    driver: local
    name: secret-rtsp

secrets:
  rtsp_user:
    external: true
  rtsp_password:
    external: true