services:
  hdd:
    build:
      context: .
      dockerfile: hdd/Dockerfile
    image: hdd:babah
    container_name: hdd-monitor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/Data/Backup:/mnt/Data/Backup
      - /mnt/Data/Syslog:/mnt/Data/Syslog
    environment:
      BACKUP_DIR: "/mnt/Data/Backup"
    ports:
      - "5000:5000"
    networks:
      rtsp-syslog-network:
        ipv4_address: 172.16.30.4

  syslog:
    build:
      context: ./syslog
      dockerfile: Dockerfile
    image: syslog-ng:babah
    container_name: syslog-ng
    ports:
      - "1514:1514/tcp"
      - "1514:1514/udp"
    restart: always
    hostname: ${SYSLOG_HOSTNAME:-syslog-ng}
    cap_add:
      - CAP_NET_BIND_SERVICE
    command: ["syslog-ng", "--foreground", "-f", "/app/syslog/config/syslog-ng.conf", "--persist-file=/app/syslog/var-run/syslog-ng.persist"]
    volumes:
      - syslog-data:/app/syslog
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - TrueNas-Syslog:/mnt/syslog
      - /home/abdullah/config/log_messages.json:/app/syslog/config/log_messages.json:ro
    networks:
      rtsp-syslog-network:
        ipv4_address: 172.16.30.5

  logrotate:
    build:
      context: ./syslog
      dockerfile: Dockerfile
    image: logrotate:babah
    container_name: logrotate
    volumes:
      - syslog-data:/app/syslog
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - TrueNas:/mnt/syslog/default/logrotate
      - /home/abdullah/config/log_messages.json:/app/syslog/config/log_messages.json:ro
    depends_on:
      - syslog
    restart: "no"

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-socket-proxy
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      LOGS: 1
    networks:
      rtsp-syslog-network:
        ipv4_address: 172.16.30.6

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: api:babah
    container_name: api-monitor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - TrueNas:/mnt/backup
      - TrueNas:/mnt/syslog
      - ./api/data:/app/data
    environment:
      LOG_DIR: "/app/data"
    ports:
      - "5001:5001"
    networks:
      rtsp-syslog-network:
        ipv4_address: 172.16.30.7

  stream:
    build:
      context: ./streamserver
      dockerfile: Dockerfile
    image: streamserver:babah
    container_name: stream-server
    volumes:
      - stream-data:/app/streamserver
      - ./streamserver/config/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/syslog/stream:/var/log/nginx
      - ./config/log_messages.json:/app/config/log_messages.json:ro
      - ./config/credentials.sh:/app/config/credentials.sh:ro
    working_dir: /app/streamserver
    ports:
      - "1935:1935" # RTMP
      - "8080:8080" # HLS
    networks:
      rtsp-syslog-network:
        ipv4_address: 172.16.30.8

networks:
  rtsp-syslog-network:
    name: babah-network
    driver: macvlan
    driver_opts:
      parent: ens3
    ipam:
      config:
        - subnet: "172.16.30.0/28"
          gateway: "172.16.30.1"

volumes:
  TrueNas:
    name: data-truenas
    driver: local
    driver_opts:
      type: none
      device: /mnt
      o: bind
  stream-data:
    name: data-stream
  syslog-data:
    name: data-syslog