#!/usr/bin/env bash

# Aktifkan error handling
set -e

# Fungsi untuk mencatat log dengan format waktu dinamis
log() {
  local timezone=$(date +%Z)
  local time_format="%d-%m-%Y %H:%M:%S"
  echo "$(date +"$time_format $timezone") - $1"
}

# Variabel
LOG_DIR="/mnt/Data/Syslog"
CONFIG_FILE="/app/logrotate/syslog-ng"  # Gunakan path absolut
OWNER="abdullah"
GROUP="abdullah"

# Pastikan direktori konfigurasi logrotate ada
log "Memastikan direktori konfigurasi logrotate ada..."
mkdir -p "$(dirname "$CONFIG_FILE")"

# Validasi direktori log
if [[ ! -d "$LOG_DIR" ]]; then
  log "Direktori log $LOG_DIR tidak ditemukan!"
  exit 1
fi

# Buat header file konfigurasi
log "Membuat file konfigurasi logrotate di $CONFIG_FILE..."
cat <<EOF > "$CONFIG_FILE"
# Generated by generate_logrotate.sh
# Date: $(date '+%d-%m-%Y %H:%M:%S')

EOF

# Scan file log di direktori
log "Memindai file log di $LOG_DIR..."
while IFS= read -r LOG_FILE; do
  cat <<EOF >> "$CONFIG_FILE"
"$LOG_FILE" {
    size 5M
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su $OWNER $GROUP
    create 0644 $OWNER $GROUP
    postrotate
        # Reload syslog-ng di kontainer 'syslog-ng' (jika nama kontainer berbeda, sesuaikan)
        docker exec syslog-ng kill -HUP 1 || true
    endscript
}

EOF
  log "Menambahkan konfigurasi untuk $LOG_FILE"
done < <(find "$LOG_DIR" -type f -name "*.log")

log "Konfigurasi logrotate selesai. File disimpan di $CONFIG_FILE."