#!/usr/bin/env bash

# Aktifkan error handling
set -e

# Variabel
LOG_DIR="/mnt/Data/Syslog"
CONFIG_FILE="/app/logrotate/syslog-ng"  # Gunakan path absolut
OWNER="abdullah"
GROUP="abdullah"

# Fungsi log untuk mencatat status
log() {
  echo "$(date '+%d-%m-%Y %H:%M:%S') - $1"
}

# Pastikan direktori konfigurasi logrotate ada
log "Memastikan direktori konfigurasi logrotate ada..."
mkdir -p "$(dirname "$CONFIG_FILE")"

# Validasi direktori log
if [[ ! -d "$LOG_DIR" ]]; then
  log "Direktori log $LOG_DIR tidak ditemukan!"
  exit 1
fi

# Buat header file konfigurasi
log "Membuat file konfigurasi logrotate di $CONFIG_FILE..."
cat > "$CONFIG_FILE" <<EOF
# Generated by generate_logrotate.sh
# Date: $(date '+%d-%m-%Y %H:%M:%S')

EOF

# Scan file log di direktori
log "Memindai file log di $LOG_DIR..."
find "$LOG_DIR" -type f -name "*.log" | while read -r LOG_FILE; do
  cat >> "$CONFIG_FILE" <<EOF
"$LOG_FILE" {
    size 5M
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su $OWNER $GROUP
    create 0644 $OWNER $GROUP
    postrotate
        docker exec syslog-ng kill -HUP 1 || true
    endscript
}

EOF
  log "Menambahkan konfigurasi untuk $LOG_FILE"
done

log "Konfigurasi logrotate selesai. File disimpan di $CONFIG_FILE."