#!/usr/bin/env bash
set -e

#####################################
# Fungsi-fungsi bantu
#####################################

# Fungsi untuk mencatat log dengan format waktu
log() {
  local timezone=$(date +%Z)
  local time_format="%d-%m-%Y %H:%M:%S"
  echo "$(date +"$time_format $timezone") - $1"
}

# Memuat isi file JSON ke variabel MESSAGES
load_messages() {
  local filepath="/app/config/log_messages.json"
  if [[ -f "$filepath" ]]; then
    MESSAGES="$(cat "$filepath")"
    log "Pesan log_messages.json berhasil diload."
  else
    log "Error: File log_messages.json tidak ditemukan. Pastikan file tersedia di /app/config."
    exit 1
  fi
}

# Ambil pesan berdasarkan path
get_message() {
  local key="$1"
  echo "$MESSAGES" | jq -r ".$key // \"\""
}

# Fungsi untuk mengganti placeholder
replace_placeholder() {
  local text="$1"
  local placeholder="$2"
  local replacement="$3"
  echo "${text//\{$placeholder\}/$replacement}"
}

#####################################
# Konfigurasi Zona Waktu
#####################################
configure_timezone() {
  local default_timezone="UTC"
  local msg

  msg=$(get_message "entrypoint.configure_timezone")
  msg=$(replace_placeholder "$msg" "timezone" "$TIMEZONE")
  log "$msg"

  if [[ -n "$TIMEZONE" ]]; then
    if [[ -f "/usr/share/zoneinfo/$TIMEZONE" ]]; then
      default_timezone="$TIMEZONE"
    else
      msg=$(get_message "entrypoint.timezone_invalid")
      msg=$(replace_placeholder "$msg" "timezone" "$TIMEZONE")
      log "$msg"
    fi
  else
    log "$(get_message "entrypoint.timezone_missing")"
  fi

  export TZ="$default_timezone"
  ln -sf "/usr/share/zoneinfo/$default_timezone" /etc/localtime
  echo "$default_timezone" > /etc/timezone

  msg=$(get_message "entrypoint.timezone_set_custom")
  msg=$(replace_placeholder "$msg" "timezone" "$default_timezone")
  log "$msg"
}

#####################################
# Variabel
#####################################
LOG_DIR="/mnt/Data/Syslog/default/logrotate"
CONFIG_FILE="/app/logrotate/syslog-ng"
OWNER="abdullah"
GROUP="abdullah"

#####################################
# Eksekusi utama
#####################################
load_messages
configure_timezone

# Pastikan direktori konfigurasi logrotate ada
log "Memastikan direktori konfigurasi logrotate ada..."
mkdir -p "$(dirname "$CONFIG_FILE")"

# Validasi direktori log
if [[ ! -d "$LOG_DIR" ]]; then
  log "Direktori log $LOG_DIR tidak ditemukan!"
  exit 1
fi

# Buat header file konfigurasi
log "Membuat file konfigurasi logrotate di $CONFIG_FILE..."
cat <<EOF > "$CONFIG_FILE"
# Generated by generate_logrotate.sh
# Date: $(date '+%d-%m-%Y %H:%M:%S %Z')

EOF

# Scan file log di direktori
log "Memindai file log di $LOG_DIR..."
while IFS= read -r LOG_FILE; do
  cat <<EOF >> "$CONFIG_FILE"
"$LOG_FILE" {
    size 5M
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su $OWNER $GROUP
    create 0644 $OWNER $GROUP
    postrotate
        docker exec syslog-ng kill -HUP 1 || true
    endscript
}

EOF
  log "Menambahkan konfigurasi untuk $LOG_FILE"
done < <(find "$LOG_DIR" -type f -name "*.log")

log "Konfigurasi logrotate selesai. File disimpan di $CONFIG_FILE."