#!/usr/bin/env bash
set -e

#####################################
# Fungsi-fungsi bantu
#####################################

# Fungsi untuk mencatat log dengan format waktu dan label zona waktu
log() {
  local offset_hours
  local zone
  local time_format="%d-%m-%Y %H:%M:%S"

  # Mendapatkan offset UTC dalam jam
  offset_hours=$(date +%z | awk '{
    sign = substr($0,1,1)
    hours = substr($0,2,2)
    minutes = substr($0,4,2)
    total = hours + (minutes / 60)
    if (sign == "-") {
      total = -total
    }
    printf "%.0f", total
  }')

  # Menentukan label zona waktu berdasarkan offset
  if [[ "$offset_hours" -eq 8 ]]; then
    zone="WITA"
  elif [[ "$offset_hours" -eq 7 ]]; then
    zone="WIB"
  else
    zone="UTC"
  fi

  echo "$(date +"$time_format") $zone - $1"
}

# Memuat isi file JSON ke variabel MESSAGES
load_messages() {
  local filepath="/app/syslog/config/log_messages.json"
  if [[ -f "$filepath" ]]; then
    MESSAGES="$(cat "$filepath")"
    log "Pesan log_messages.json berhasil diload."
  else
    log "Error: File log_messages.json tidak ditemukan. Pastikan file tersedia di /app/syslog/config."
    exit 1
  fi
}

# Ambil pesan berdasarkan path
get_message() {
  local key="$1"
  echo "$MESSAGES" | jq -r ".$key // \"\""
}

#####################################
# Variabel
#####################################
LOG_ROOT="/mnt/Data/Syslog"
CONFIG_FILE="/app/syslog/logrotate/syslog-ng"
OWNER="abdullah"
GROUP="abdullah"

#####################################
# Eksekusi utama
#####################################
load_messages

# Pastikan direktori konfigurasi logrotate ada
log "Memastikan direktori konfigurasi logrotate ada..."
mkdir -p "$(dirname "$CONFIG_FILE")"

# Validasi direktori log root
if [[ ! -d "$LOG_ROOT" ]]; then
  log "Direktori log root $LOG_ROOT tidak ditemukan!"
  exit 1
fi

# Periksa apakah file konfigurasi logrotate sudah ada
if [[ -f "$CONFIG_FILE" ]]; then
  log "File konfigurasi logrotate $CONFIG_FILE sudah ada. Mengabaikan pembuatan ulang."
else
  # Buat header file konfigurasi
  log "Membuat file konfigurasi logrotate di $CONFIG_FILE..."
  cat <<EOF > "$CONFIG_FILE"
# Generated by generate_rotate.sh
# Date: $(date '+%d-%m-%Y %H:%M:%S %Z')

EOF

  # Scan semua file log di subdirektori
  log "Memindai semua file log di $LOG_ROOT..."
  while IFS= read -r LOG_FILE; do
    cat <<EOF >> "$CONFIG_FILE"
"$LOG_FILE" {
    size 5M
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su $OWNER $GROUP
    create 0644 $OWNER $GROUP
    postrotate
        docker exec syslog-ng kill -HUP 1 || true
    endscript
}

EOF
    log "Menambahkan konfigurasi untuk $LOG_FILE"
  done < <(find "$LOG_ROOT" -type f -name "*.log")

  log "Konfigurasi logrotate selesai. File disimpan di $CONFIG_FILE."
fi